### ISSUE TITLE
Theme does not cover whole IDE

### ISSUE THREAD

**Issue by cappuchinese** [elliotwaite/jetbrains-cyberpunk-theme#4]
Happened right after I downloaded 1.0.11
Tried restarting the IDE, but didn't work
![Screenshot from 2022-05-31 17-34-22](https://user-images.githubusercontent.com/80789452/171212720-2a721968-3883-4db2-99d2-89688ac2a013.png)
This is PyCharm, not sure if other IDEs have the same trouble

**Comment by cappuchinese** [comment]
Don't mind the code that I wrote :grimacing:

**Comment by elliotwaite** [comment]
Thanks for reporting this.

Can you let me know if both of these settings are set in the preferences:

`Preferences > Appearance & Behavior > Appearance > Theme: Cyberpunk Theme`

`Preferences > Editor > Color Scheme > Scheme: Cyberpunk Theme`

**Comment by cappuchinese** [comment]
Oh that was it! :D
After the update, the theme got turned off for some reason. Usually never happens...
Sorry for your time! :sweat_smile:

**Comment by elliotwaite** [comment]
I'm glad to hear that fixed it. That's strange that the theme got turned off after the update, maybe it's related to a bug in the IDE code, but I'm not sure.

No worries, feel free to open an issue whenever you encounter unexpected behavior or have any other questions. I'll be happy to help.
